---
- name: Deploy
  hosts: all
  tasks:
    - name: Enable VNC
      become: false
      block:
        - ansible.builtin.command: gsettings set org.gnome.desktop.screensaver idle-activation-enabled false
        - ansible.builtin.command: gsettings set org.gnome.desktop.screensaver lock-enabled false
        - ansible.builtin.command: grdctl vnc enable
        - ansible.builtin.command: grdctl vnc set-auth-method password
        - ansible.builtin.command: grdctl vnc set-password {{ vnc_password }}

    - name: Update OS and install deps
      block:
        - ansible.builtin.apt_key:
            url: https://apt.kitware.com/keys/kitware-archive-latest.asc
        - ansible.builtin.apt_repository:
            repo: deb https://apt.kitware.com/ubuntu/ {{ ansible_facts["distribution_release"] }} main
        - ansible.builtin.apt:
            upgrade: dist
            update_cache: true
        - ansible.builtin.apt:
            name: "{{ item }}"
          loop: "{{ base_packages }}"
        - ansible.builtin.stat:
            path: /var/run/reboot-required
          register: reboot_required_file
        - reboot:
          when: reboot_required_file.stat.exists == true

    - name: Install gitlab-runner
      block:
        - ansible.builtin.get_url:
            url: https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-arm64
            dest: /usr/local/bin/gitlab-runner
            mode: "0775"
        - ansible.builtin.user:
            name: gitlab-runner
            comment: 'Gitlab Runner'
            shell: /bin/bash
        - ansible.builtin.command: gitlab-runner install --user=gitlab-runner --working-directory=/home/gitlab-runner
          ignore_errors: yes
        - ansible.builtin.file:
            state: directory
            path: /etc/systemd/system/gitlab-runner.d
        - ansible.builtin.copy:
            content: "[Service]\nEnvironment=HOME=/root/gitlab-runner"
            dest: /etc/systemd/system/gitlab-runner.d/override.conf
            force: no
        - ansible.builtin.systemd:
            name: gitlab-runner
            state: restarted
            daemon_reload: true
            enabled: true

    - name: Add gpus in gitlab runner
      block:
        - ansible.builtin.stat:
            path: /etc/gitlab-runner/config.toml
          register: sym
        - ansible.builtin.lineinfile:
            path: /etc/gitlab-runner/config.toml
            insertafter: '^\s*[runners.docker]$'
            regexp: '^\s*gpus = "all"'
            line: '    gpus = "all"'
          when: sym.stat.islnk is defined

  vars:
    base_packages:
      - btop
      - build-essential
      - ca-certificates
      - cmake
      - curl
      - docker
      - gpg
      - tmate
      - tmux
      - vim
  roles:
   - role: hifis.toolkit.unattended_upgrades
     unattended_origins_patterns:
       - 'origin=Ubuntu,archive=${distro_codename}-security'
       - 'o=Ubuntu,a=${distro_codename}-updates'
     unattended_package_blacklist: []
     unattended_mail: 'root@example.com'
