---
- name: Deploy
  hosts: all
  vars:
    base_packages:
      - btop
      - build-essential
      - ca-certificates
      - cmake
      - curl
      - docker
      - gpg
      - tmate
      - x11vnc
      - tmux
      - vim
  tasks:
    - community.general.parted:
        device: /dev/nvme0n1
        number: 1
        state: present
        fs_type: ext4

    - community.general.filesystem:
        fstype: ext4
        dev: /dev/nvme0n1p1

    - ansible.posix.mount:
        path: /data
        src: /dev/nvme0n1p1
        fstype: ext4
        opts: defaults,nofail
        state: present

    - name: Enable VNC
      become: false
      ansible.builtin.shell: |
        gsettings set org.gnome.desktop.screensaver idle-activation-enabled false
        gsettings set org.gnome.desktop.screensaver lock-enabled false

    - name: Update OS and install deps
      block:
        - ansible.builtin.apt_key:
            url: https://apt.kitware.com/keys/kitware-archive-latest.asc
        - ansible.builtin.apt_repository:
            repo: deb https://apt.kitware.com/ubuntu/ {{ ansible_facts['distribution_release'] }} main
        - ansible.builtin.apt:
            upgrade: dist
            update_cache: true
        - ansible.builtin.apt:
            name: "{{ item }}"
          loop: "{{ base_packages }}"
        - ansible.builtin.stat:
            path: /var/run/reboot-required
          register: reboot_required_file
        - reboot:
          when: reboot_required_file.stat.exists == true

    - ansible.builtin.copy:
        src: x11vnc.service
        dest: /etc/systemd/system/x11vnc.service
      notify:
        - restart x11vnc

    - ansible.builtin.copy:
        src: docker-daemon.json
        dest: /etc/docker/daemon.json
      notify:
        - restart docker

  handlers:
    - name: restart x11vnc
      ansible.builtin.systemd:
        daemon-reload: true
        name: x11vnc
        enabled: true
        state: restarted

    - name: restart docker
      ansible.builtin.systemd:
        name: docker
        state: restarted

- name: unattended_upgrades
  hosts: all
  roles:
   - role: hifis.toolkit.unattended_upgrades
     unattended_origins_patterns:
       - 'o=Ubuntu,a=${distro_codename}'
       - 'o=Ubuntu,a=${distro_codename}-security'
       - 'o=Ubuntu,a=${distro_codename}-updates'
       - 'o=Ubuntu,a=${distro_codename}-backports'
       - 'o=Nvidia,a=stable'
       - 'o=Docker,a=${distro_codename}'
     unattended_package_blacklist: []
